---

# Usage: This file defines rules for generating commit messages.

rules:
  commit-message:
    format: "{type}({scopes}): {description} in {targets}"
    examples:
      - "feat(yaml): Create initial commit message format rules in 1 YAML file"
      - "refactor(js): Update emojis in theme toggle in 1 JS file"
      - "chore(html): Standardize comment line formatting in 3 HTML files"
      - "teach(css): Simplify comment for paragraph styles in 1 CSS file"
      - "a11y(html): Add ARIA-current to active nav link in 1 HTML file"
      - "seo(html): Add site name to page title in 2 HTML files"
      - "security(html): Add <noscript> warning in 1 HTML file"
      - "fix(html): Correct social media preview image urls in 5 HTML files"
      - "test(html): Test functionality of X card tags in 2 HTML files"
      - "lint(html): Escape & as &amp; to satisfy html linter in 1 HTML file"
      - "delete(html, css): Remove styles in 1 HTML file and 1 CSS file"
      - "style(css): Update h1 color and comment in 1 CSS file"
      - "content(html): Update footer text in 5 HTML files"
      - "job(assets): Digitize Phi: Update assets for day 2 in 4 PNG files"
    case-style: "quark-case"
    quark-case:
      type:
        case: lower  # {type} always lowercase, e.g., "feat", "refactor"
      scopes:
        case: lower  # {scope} always lowercase, e.g., "html", "js"
      description:
        case: sentence  # Capitalize first letter, e.g., "Add job to types"
      targets:
        case: upper-file-type  # Only the file type (e.g. HTML, JS) is uppercase
    types:
      - feat: "Adds a new feature or functionality"
      - refactor: "Enhances code structure without behavior change"
      - chore: "Routine maintenance or formatting tasks (not documentation)"
      - teach: "Updates or improves comments, docs, or explanatory content"
      - a11y: "Improves accessibility"
      - seo: "Enhances search engine optimization"
      - security: "Addresses security concerns"
      - fix: "Corrects a bug or issue"
      - test: "For testing functionality in production"
      - lint: "Applies linting or formatting fixes"
      - delete: "Removes code, files, or assets"
      - style: "Modifies visual presentation or UI styles"
      - content: "Modifies page content such as text or media"
      - job: "Execution of a scheduled or automated task"
    scopes:
      - html
      - js
      - css
      - assets
      - json
      - yaml
      - md
      - xml
      - txt
      - py
    targets:
      description: "List of affected items with counts and types"
      format: |
          "{number} {target} {plurality}[ and {number} {target} {plurality}]*"
      examples:
        - "1 HTML file"
        - "2 JS files"
        - "1 HTML file and 1 CSS file"
        - "3 HTML files and 2 CSS files"
        - "1 JPG file"
        - "1 PNG file"
        - "1 JSON file"
        - "1 YAML file"
        - "1 MD file"
        - "1 XML file"
        - "1 TXT file"
        - "1 PY file"
        - "1 MP3 file"
        - "1 MOV file"
        - "1 MP4 file"
    description:
      tense: active
